name: mink_dart_utils
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.2.3

dev_dependencies:
  lints: ^2.1.0
  custom_lint: any
  minklint: any
  meta: ^1.17.0
  test: ^1.24.0

dependencies:
  collection: ^1.18.0
  filterinio:
    git: git@github.com:MinkTec/filterinio
